import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params
    const supabase = await createClient()
    
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Fetch letter and verify ownership
    const { data: letter, error: letterError } = await supabase
      .from('letters')
      .select('*, profiles(full_name)')
      .eq('id', id)
      .single()

    if (letterError || !letter) {
      return NextResponse.json({ error: 'Letter not found' }, { status: 404 })
    }

    // Verify user can access this letter (owner or admin)
    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (letter.status !== 'approved') {
      return NextResponse.json({ 
        error: 'Only approved letters can be downloaded as PDF' 
      }, { status: 403 })
    }

    if (letter.user_id !== user.id && profile?.role !== 'admin') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    // TASK 7: Generate proper PDF using HTML-to-PDF approach
    // For now, we'll use a simple HTML approach that can be printed as PDF
    // In production, consider using puppeteer or @react-pdf/renderer
    const content = letter.final_content || letter.ai_draft_content || ''
    
    // Create professional letterhead HTML
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${letter.title}</title>
  <style>
    @page {
      size: A4;
      margin: 1in;
    }
    
    body { 
      font-family: 'Times New Roman', serif; 
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      margin: 0;
      padding: 0;
    }
    
    .letterhead {
      text-align: center;
      border-bottom: 2px solid #003366;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    
    .letterhead h1 {
      margin: 0;
      font-size: 18pt;
      color: #003366;
      font-weight: bold;
    }
    
    .letterhead p {
      margin: 5px 0;
      font-size: 10pt;
      color: #666;
    }
    
    .date {
      text-align: right;
      margin-bottom: 30px;
      font-size: 11pt;
    }
    
    .content { 
      white-space: pre-wrap;
      text-align: justify;
      margin-bottom: 40px;
    }
    
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #ccc;
      font-size: 9pt;
      color: #666;
      text-align: center;
    }
    
    .signature-block {
      margin-top: 60px;
    }
    
    @media print {
      body {
        margin: 0;
      }
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <div class="letterhead">
    <h1>TALK-TO-MY-LAWYER</h1>
    <p>Professional Legal Document Services</p>
    <p>Attorney-Reviewed Legal Correspondence</p>
  </div>
  
  <div class="date">
    ${new Date(letter.created_at).toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    })}
  </div>
  
  <div class="content">${content}</div>
  
  <div class="signature-block">
    <p>Sincerely,</p>
    <br><br>
    <p>_______________________________</p>
    <p>${letter.profiles?.full_name || 'Sender'}</p>
  </div>
  
  <div class="footer">
    <p><strong>Document ID:</strong> ${letter.id}</p>
    <p>This document has been reviewed and approved by a licensed attorney.</p>
    <p>Generated by Talk-To-My-Lawyer | www.talk-to-my-lawyer.com</p>
  </div>
  
  <script>
    // Auto-print dialog for PDF generation
    window.onload = function() {
      window.print();
    }
  </script>
</body>
</html>`

    // Return HTML that will trigger print dialog for PDF generation
    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `inline; filename="${letter.title.replace(/[^a-z0-9]/gi, '_')}.html"`
      }
    })

  } catch (error) {
    console.error('[PDF] Generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    )
  }
}