import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params
    const supabase = await createClient()
    
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Fetch letter and verify ownership
    const { data: letter, error: letterError } = await supabase
      .from('letters')
      .select('*, profiles(full_name)')
      .eq('id', id)
      .single()

    if (letterError || !letter) {
      return NextResponse.json({ error: 'Letter not found' }, { status: 404 })
    }

    // Verify user can access this letter (owner or admin)
    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (letter.status !== 'approved') {
      return NextResponse.json({ 
        error: 'Only approved letters can be downloaded as PDF' 
      }, { status: 403 })
    }

    if (letter.user_id !== user.id && profile?.role !== 'admin') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const content = letter.final_content || letter.ai_draft_content || ''
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Times New Roman', serif; padding: 40px; line-height: 1.6; }
    .header { text-align: right; margin-bottom: 30px; }
    .content { white-space: pre-wrap; }
    .footer { margin-top: 50px; border-top: 1px solid #ccc; padding-top: 20px; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <strong>${letter.title}</strong><br>
    Date: ${new Date(letter.created_at).toLocaleDateString()}
  </div>
  <div class="content">${content}</div>
  <div class="footer">
    Generated by Talk-To-My-Lawyer<br>
    This document has been reviewed and approved by a licensed attorney.
  </div>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="${letter.title.replace(/[^a-z0-9]/gi, '_')}.html"`
      }
    })

  } catch (error) {
    console.error('[v0] PDF generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    )
  }
}
